### ISSUE TITLE
Bump httpx version

### ISSUE THREAD

**Issue by dmalis** [uploadcare/pyuploadcare#243] opened 2023-06-26 10:42 UTC
The conflict is caused by:
    The user requested httpx==0.24.1
    pyuploadcare 4.0.0 depends on httpx<0.24.0 and >=0.23.0; python_version >= "3.7" and python_version < "4.0"

**Comment by evgkirov** [comment] 2023-06-26 17:48
Duplicate of #211 

I will treat this as a priority escalation.

**Closed** 2023-07-03 14:34 UTC
